### ISSUE TITLE
Seg fault

### ISSUE THREAD

**Issue by nsohail19** [splatlab/mantis#12] opened 2018-05-29 13:00 UTC
Whenever I try to build with mantis, I end up with a segmentation fault. This happens regardless of if I use NH=1 when I make mantis. This is what it outputs whenever I use a command like this:

./mantis build -i HGGs/testing/incqfs.lst -c HGGs/testing/experiment_cutoffs.lst -o HGGs/mantis_output/
Reading CQF 0 Seed 2038074761
Segmentation fault

My input file looks like this:

HGGs/exact_squeakr_output/SRR7050121_1.fastq.gz_exact.ser
HGGs/exact_squeakr_output/SRR7050122_1.fastq.gz_exact.ser

And my experimental cutoff file looks like this:

SRR7050121_1.fastq.gz 20
SRR7050122_1.fastq.gz 20

**Comment by prashantpandey** [comment] 2018-06-13 00:30
Hey @rsharris, what is the k-mer size you are using?

**Comment by rsharris** [comment] 2018-06-13 00:38
k-mer size 20

**Comment by rsharris** [comment] 2018-06-13 00:41
By which I mean, the CQFs were made by squeakr with -k 20.

I don't see any command line setting for that in mantis itself.  Is that something I'd need to fiddle with at mantis build time?

**Comment by prashantpandey** [comment] 2018-06-13 00:45
No, Mantis uses the Squeakr input to construct the index and doesn't need to know the k-mer size. 
One main reason why it hung for so long before crashing is that the size of the CQF was provisioned smaller than what it needs.
Are the cutoffs same as in the original SBT paper? 

Also, it mmaps all the Squeakr files. So going out-of-memory because of reading so many files should not be the reason.

**Comment by rsharris** [comment] 2018-06-13 00:56
"Are the cutoffs same as in the original SBT paper?"

They're close, but not exactly the same.  I didn't contact S/K to ask for the cutoffs.  Instead, I used jellyfish to get the kmer abundance distribution, and picked the cutoff to agree with the number of 1s in the corresponding BF.  I tested those cuttoffs on BFs with a different hash function.  They produce reasonable results, though for a handfull of BFs no cutoff produced a BF with similar occupancy to the S/K one.  I surmised that they probably had an unnoticed transmission error getting the fastq file. I believe you noted something similar in the mantis paper.

I've got to leave now, until tomorrow afternoon.

**Comment by prashantpandey** [comment] 2018-06-14 03:48
Hi @rsharris , I guess cutoffs in the SBT paper were decided based on the size of the fastq files. We used the similar method to calculate cutoffs. For us, the only difference (maybe) compared to the SBT was in choosing the inclusiveness (']' or ')') of the cutoff ranges. We have mentioned that in the paper.
The cutoffs we used in our experiments is here: [cutoff file](https://github.com/splatlab/mantis/blob/master/raw/experiment_cutoffs.lst). You can see if yours are same/different.  

I don't know how it will affect them when you decide based on the number of 1s in the Bloom filter. 

However, irrespective of the cutoff issue, I will try and write a patch with more logging (hopefully by tomorrow) so that we can get to the bottom of this segfault issue. I will mention here when the patch is ready to be tested.

Thanks,
Prashant

**Comment by rsharris** [comment] 2018-06-14 15:47
Regarding the cutoffs, I'd compared those to yours a few months ago.  What I found was that they were the same for about half the fasta files.  When they are different, my threshold is usually lower (which permits more kmers). There are a couple dozen outliers for which the reverse is true.

For example, for 449 files I have a threshold of 20, mantis has 50.  For 366 I have 10 instead of 20, and for 278 I have 3 instead of 10.

I also noticed that your cutoffs file contains paths, whereas mine just contains file names.  That's not what's causing the problem, is it?

I'll try your thresholds to see whether that exorcizes the problem.

Thinking out loud ... At this stage of my manuscript (hopefully close to completion), it wouldn't be feasible to change the thresholds for the other solutions I'm using.  I'd have to think about whether using different thresholds for mantis would affect the comparison.

**Comment by rsharris** [comment] 2018-06-14 15:52
I wrote:
> When they are different, my threshold is usually lower (which permits more kmers).

What I meant by that is that more kmers qualify to be included in the data structure.  I wasn't making any judgement as to whether more kmers is better or worse.

**Comment by rsharris** [comment] 2018-06-14 16:48
I wrote:
`I'll try your thresholds to see whether that exorcizes the problem.`

Looks like that would prevent the problem.  It has proceeded further than before; for example it has reported this. 
```
Number of eq classes found after sampling 7663546
Reinitializing colored DBG after the sampling phase.
Constructing the colored dBG.
```
and is now reporting things like
`Kmers merged: 50000000 Num eq classes: 7663546 Total time: 2555`

So ... if the number of distinct kmers, or maybe the number of equivalence classes, is too large with my cutoffs, what would I change in the code to accommodate that?

**Comment by prashantpandey** [comment] 2018-06-15 16:00
Hi @rsharris , were you able to finish running Mantis with the new cutoffs?
Also, if you want to use your cutoffs (which apparently is resulting in more k-mers) then you need to increase the size of the output CQF. 

Currently, the final CQF size is hardcoded to 16B slots (2^34). (https://github.com/splatlab/mantis/blob/master/include/cqf.h#L35).
You can increase that to 35 or 36 and see if the process goes past the sampling phase.

Note: We already have a fix to dynamically estimate the size of the output CQF and resize the CQF. We will release the fix soon.

Thanks,
Prashant

**Comment by rsharris** [comment] 2018-06-15 16:15
`were you able to finish running Mantis with the new cutoffs?`
Yes.  Actually that just finished about a half hour ago.  Wall time was 23.5 hours.

It reported "Final colored dBG has 3800824722 k-mers and 233790331 equivalence classes"
Total of all files in the -o directory is 36.8G. Is that consistent with what you get on the Solomon database?

(I ask this only in case it suggests I've done something wrong) To the extent that I understand what the output it telling me, it seems to have estimated 7.6M eq classes, but ended up with 234M.  Is that plausible?  What I think I recall from the paper is that the sampling step is likely to find most of the highly abundant eq classes (so they can be assigned to small numbers), but I don't recall if it said anything about how good the estimated count is.

I've run one 10-transcript query with this, and it seems to have worked (I haven't checked the results vs other tools, but nothing seems out of the ordinary).

If the results pass a sanity check, I'll make the change you mention and try using my thresholds.

Thanks!

**Comment by prashantpandey** [comment] 2018-06-15 16:28
The output seems correct although slightly on the higher side. We saw ~3.69B k-mers and ~220M eq classes. 
@rsharris Can you list files in the -o directory. Becuase it does produce some extra files in the output directory that should not be counted towards the final index size.
Basically, index includes a CQF file (with .ser extension) and some (maybe 11) eq class files (with .cls extension).

**Comment by prashantpandey** [comment] 2018-06-15 16:37
Also, where are you storing the input Squeakr files? That might change the total time.

**Comment by rsharris** [comment] 2018-06-15 16:56
`The output seems correct although slightly on the higher side. We saw ~3.69B k-mers and ~220M eq classes.`
I wonder why they would be different. At this point, the only difference I can think of is that I eliminated the fastq files that have no kmers. Guessing: maybe you've changed hash functions since the manuscript? (wouldn't make _that_ big a difference) In any case, I don't think difference is significant.

> Can you list files in the -o directory
```
0_eqclass_rrr.cls   1,079,127,251
1_eqclass_rrr.cls   1,298,598,923
2_eqclass_rrr.cls   1,344,464,731
3_eqclass_rrr.cls   1,385,134,787
4_eqclass_rrr.cls   1,417,632,443
5_eqclass_rrr.cls   1,446,726,443
6_eqclass_rrr.cls   1,472,783,867
7_eqclass_rrr.cls   1,499,871,251
8_eqclass_rrr.cls   1,521,789,283
9_eqclass_rrr.cls   1,542,666,171
10_eqclass_rrr.cls  1,560,849,571
11_eqclass_rrr.cls  1,082,711,619
dbg_cqf.ser        17,449,635,968
sampleid.lst               38,322
eqclass_dist.lst    2,700,086,398
```

> Also, where are you storing the input Squeakr files?
Good question. They're "on disk" but I haven't given much thought to the properties of the disk/file system (other than space).

**Comment by rob-p** [comment] 2018-06-15 17:00
Hi @rsharris,

I think this file `eqclass_dist.lst` is actually something that we ended up writing out to make some figures for the paper, but it has no relation to the actual index.  It should be safe to ignore / delete it.  Is this right, @prashantpandey ?

**Comment by prashantpandey** [comment] 2018-06-15 17:03
Yes, we don't need ".lst" files in the index.

**Comment by rsharris** [comment] 2018-06-15 17:05
Cool.  I've changed my pipeline to remove eqclass_dist.lst after the build.

**Comment by nsohail19** [comment] 2018-06-15 17:11
Hello,

I do not think that the segmentation faults that I have been getting are the same as the ones rsharris has been getting. When I try to build mantis, it seg faults almost immediately. The part of the print statement the begins "Sample id" never appears when I use it since it always seg faults before that point. I have only been running it with 2 CQFs from squeakr because I wanted to test and make sure that it works, so there should not be a memory issue either.

**Comment by rsharris** [comment] 2018-06-15 21:06
```
Currently, the final CQF size is hardcoded to 16B slots (2^34).
You can increase that to 35 or 36 and see if the process goes past the sampling phase.
```

FWIW, 35 wasn't enough in my case, but 36 appears to be working.

For 35, it got stuck after "Sampling eq classes based on 67108864 kmers"; I gave it ten minutes then killed it.  In successful runs it seems to only take about 5 minutes to progress from that message.

Thanks again.

**Comment by rsharris** [comment] 2018-06-15 21:07
@nsohail19 
`I do not think that the segmentation faults that I have been getting are the same as the ones rsharris has been getting.`

Sorry about that. It seems I've hijacked your issue.

**Comment by rsharris** [comment] 2018-06-20 13:32
Following up on this statement:
> FWIW, 35 wasn't enough in my case, but 36 appears to be working.

When I ran with NUM_Q_BITS=36, it seems to have stalled after reporting this:
```
Home slot: 2113216197 Insertion slot: 2113216199 Difference: 2 Fraction done: 0.030751
Kmers merged: 290000000 Num eq classes: 28296637 Total time: 6427
```

It was stuck there for more than a day before I killed it.  Though I didn't notice it at the time, some process was eating up all the memory on this machine (there are a couple other users).  Can't say for certain whether it was mantis.

In any case, I'm not going to pursue this further.  For my manuscript, I'll use the successful mantis build with thresholds from the mantis repo, and NUM_Q_BITS=34.

**Comment by prashantpandey** [comment] 2018-06-20 13:46
@nsohail19 , can you send your cutoff file? I can try and reproduce and fix the issue. Thanks!

**Comment by nsohail19** [comment] 2018-06-20 16:08
My cutoff file is only two lines:
```
SRR7050121_1.fastq.gz 20
SRR7050122_1.fastq.gz 20
```
This is what my input file was like:
```
HGGs/exact_squeakr_output/SRR7050121_1.fastq.gz_exact.ser
HGGs/exact_squeakr_output/SRR7050122_1.fastq.gz_exact.ser
```

**Comment by prashantpandey** [comment] 2018-06-20 18:38
@nsohail19 you would need to share the fastq files as well for me to reproduce.

**Comment by prashantpandey** [comment] 2018-06-20 18:38
@rsharris , could you share the cutoff file on 2652 data sets so that I can reproduce and fix the issue?

**Comment by prashantpandey** [comment] 2018-06-20 18:49
@nsohail19 , I guess in your case the problem is in the fact that file names contain multiple ".".

**Comment by prashantpandey** [comment] 2018-06-20 19:10
@nsohail19 , I guess I figured out the issue that you are facing. It's because of construction code is not able to map files from the input list to the cutoff list. 
I am planning on writing a fix for that. Will update when I push it.

**Comment by rsharris** [comment] 2018-06-20 19:20
@prashantpandey I've (now) sent my cutoff files to your email address listed in the manuscript.

Thanks.

**Comment by prashantpandey** [comment] 2018-07-05 22:15
@nsohail19 , Hi we have released a new version in which we have changed the format of the input Squeakr files and cutoffs. Now, we use only one file to specify the paths to the input Squeakr files and their cutoffs. Could you please try and see if the bug is still there?

**Comment by hmusta** [comment] 2018-07-25 17:20
The latest version of the code still appears to segfault most of the time when I run it on dummy data, but I'm not sure if it's related to this issue. I posted some details in issue #15

**Closed** 2018-11-08 20:52 UTC
